name: Daily jobs
permissions:
  contents: read
  pull-requests: write
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  download-translations-from-crowdin:
    name: Download translations from crowdin
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Sync with crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          skip_untranslated_strings: true
          localization_branch_name: crowdin-sync
          create_pull_request: true
          commit_message: Sync translations
          pull_request_title: Sync translations
          pull_request_body: '_Synced by GitHub actions from [Crowdin](https://crowdin.com/project/delta-app)_'
          pull_request_reviewers: supershadoe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PAT }}
